#!/bin/bash


gfortran tanto_lavoro_solo_zsrt_autovalori_noti.f90 qzhes.o qzit.o qzval.o qzvec.o rgg.o -o tanto_lavoro_solo_zsrt_autovalori_noti -lpgplot -lX11

 ./tanto_lavoro_solo_zsrt_autovalori_noti > resoconto_tanto_lavoro_solo_autovalori_noti.txt
